export * from './dynamo/client.js';
export * from './dynamo/visits.js';
export * from './dynamo/dashboard.js';
export * from './dynamo/surveillance.js';
export * from './dynamo/clinical.js';
export * from './dynamo/logistics.js';
export * from './dynamo/feedback.js';
export * from './dynamo/documents.js';
export * from './dynamo/analytics.js';
